config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get '/friendships/:id', to: 'patients#show', as: 'patient'
  devise_for :users

  root 'home#index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :profiles
  resources :friendships do
    collection do
      post :block
      post :unblock
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show]
  before_action :set_user_profile, only: [:edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all.where.not(id: current_user.profile.id)

  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    # binding.pry
    # redirect_to edit_profile_path(@profile) unless current_user.profile.id == params[:id]
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        # format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        # format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    # binding.pry
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        # format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        # format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_user_profile
      current_user.profile = Profile.create(user_id: current_user.id, id: current_user.id) unless current_user.profile.present?
      @profile = current_user.profile
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :age, :gender, :sex_preferences, :tags, :bio).merge(user_id: current_user.id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def full_name(profile)
    profile.last_name + ' ' + profile.first_name
  end
end

app/views/profiles/_form.html.erb
<div class="login-form">
  <%= form_with(model: profile, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :age %>
        <%= form.text_field :age, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :gender %>
        <%= form.text_field :gender, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :sex_preferences %>
        <%= form.text_field :sex_preferences, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :tags %>
        <%= form.text_field :tags, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :bio %>
        <%= form.text_area :bio, size: "30x10", class: 'form-control' %>
      </div>
      <% form.hidden_field :user_id, value: current_user.id %>
    <% if profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

        <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit "Save", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>

app/views/profiles/_profile.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= full_name(profile) %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://www.bitgab.com/uploads/profile/files/default.png" class="img-circle img-responsive"> </div>
      <div class=" col-md-9 col-lg-9 ">
        <table class="table table-user-information">
          <tbody>
          <tr>
            <td>Age:</td>
            <td><%= profile.age %></td>
          </tr>
          <tr>
            <td>Gender:</td>
            <td><%= profile.gender %></td>
          </tr>
          <tr>
            <td>Sex Preferences</td>
            <td><%= profile.sex_preferences %></td>
          </tr>
          <tr>
          <tr>
            <td>Tags</td>
            <td><%= profile.tags %></td>
          </tr>
          <tr>
            <td>Bio</td>
            <td><%= simple_format profile.bio %></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><a href="mailto:info@support.com">info@support.com</a></td>
          </tr>
          <td>Phone Number</td>
          <td>123-4567-890(Landline)<br><br>555-4567-890(Mobile)
          </td>
          </tr>

          </tbody>
        </table>
        <% relationships = current_user.friendship_status(profile.user) %>
        <% case relationships %>
        <% when 'friends' %>
          <%= 'You are already friends' %>
          <%= button_to "Remove", current_user.friendship_with(profile.user), method: :delete, class: 'btn btn-danger' %>
        <% when 'his block' %>
          <%= 'This user added you to Black list. Sorry :(' %>
        <% when 'your block' %>
          <%= 'You have blocked this user' %>
          (<%= link_to "Unblock", unblock_friendships_path(unblock_user: profile.user), method: :post %>)
        <% when 'your request' %>
          <%= 'You have already sent a friend request' %>
          <%= button_to "Remove", current_user.friendship_with(profile.user), method: :delete, class: 'btn btn-danger' %>
        <% when 'his request' %>
          <%= 'This user wants to be friends with you' %>
          (<%= link_to "Block", block_friendships_path(block_user: profile.user), method: :post %>)
          <%= button_to "Add Friend", friendships_path(friend_id: profile.user), method: :post, class: 'btn btn-success' %>
        <% else %>
        <%= button_to "Add Friend", friendships_path(friend_id: profile.user), method: :post, class: 'btn btn-success' %>
        <% end %>

      </div>
    </div>
  </div>
  <div class="panel-footer">
    <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
    <span class="pull-right">
                        <%= button_to 'Edit my profile', edit_profile_path(profile), method: :get, class: 'btn btn-primary' if profile == current_user.profile %>
                    </span>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile <%= @profile.id %></h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>
  <%= render 'profile', profile: profile %>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<br><br><br><br>
  <%= render 'profile', profile: @profile %>