config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get '/friendships/:id', to: 'patients#show', as: 'patient'
  devise_for :users

  root 'home#index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :profiles
  resources :friendships do
    collection do
      post :block
      post :unblock
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validates :user_id, uniqueness: { scope: :friend_id }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @users = (current_user.friends + current_user.inverse_friends).uniq
    @his_block = []
    @your_block = []
    @friends = []
    @your_request = []
    @his_request = []
    @users.each do |user|
      status = current_user.friendship_status(user)
      if status == 'his block'
        @his_block << user
      elsif status == 'your block'
        @your_block << user
      elsif status == 'friends'
        @friends << user
      elsif status == 'your request'
        @your_request << user
      elsif status == 'his request'
        @his_request << user
      end
    end
  end

  def create

    begin
      @friendship = current_user.friendships.build(friend_id: params[:friend_id])
      if @friendship.save
        flash[:notice] = "Added friend."
      else
        flash[:notice] = "Unable to add friend."
      end
      redirect_back(fallback_location: friendships_path)
    rescue ActiveRecord::RecordNotUnique
      flash[:notice] = "This user has already been added."
      redirect_back(fallback_location: friendships_path)
    end
  end

  def destroy
    # begin
      @friendship = current_user.friendships.find(params[:id])
    # rescue
    #   @friendship = current_user.inverse_friendships.find(params[:id])
    # end
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_back(fallback_location: friendships_path)
  end

  def block
    friendship = current_user.friendships.find_by(friend_id: params[:block_user])
    friendship = current_user.friendships.build(friend_id: params[:block_user]) if friendship.nil?
    friendship.update_attribute(:blocked_by_user_id, current_user.id)
    flash[:notice] = "Friendship was blocked."
    redirect_back(fallback_location: friendships_path)
  end

  def unblock
    friendship = current_user.friendships.find_by(friend_id: params[:unblock_user])
    friendship.update_attribute(:blocked_by_user_id, 0)
    flash[:notice] = "Friendship was unblocked."
    redirect_back(fallback_location: friendships_path)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<h2>Your Friends</h2>
<ul>
  <%= 'Not found' if @friends.count == 0 %>
  <% for friend in @friends %>
    <li>
      <%= link_to "#{friend.email}", profile_path(friend.profile), method: :get %>
      (<%= link_to "remove", current_user.friendship_with(friend), method: :delete %>)
    </li>
  <% end %>
</ul>
<hr>
<h2>Your requests for friendship</h2>
<ul>
  <%= 'Not found' if @your_request.count == 0 %>
  <% for friend in @your_request %>
    <li>
      <%= friend.email %>
      (<%= link_to "remove", current_user.friendship_with(friend), method: :delete %>)
    </li>
  <% end %>
</ul>
<hr>
<h2>Users who want to be friends with you</h2>
<ul>
  <%= 'Not found' if @his_request.count == 0 %>
  <% for friend in @his_request %>
    <li>
      <%= friend.email %>
      (<%= link_to "Add Friend", friendships_path(friend_id: friend), method: :post %>)
      (<%= link_to "block", block_friendships_path(block_user: friend), method: :post %>)
    </li>
  <% end %>
</ul>
<hr>
<h2>Blocked users</h2>
<ul>
  <%= 'Not found' if @your_block.count == 0 %>
  <% for friend in @your_block %>
    <li>
      <%= friend.email %>
      (<%= link_to "Unblock", unblock_friendships_path(unblock_user: friend), method: :post %>)
    </li>
  <% end %>
</ul>
<hr>
<h2>Users who have blocked you</h2>
<ul>
  <%= 'Not found' if @his_block.count == 0 %>
  <% for friend in @his_block %>
    <li>
      <%= friend.email %>
    </li>
  <% end %>
</ul>
<hr>